version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      commit-message:
        prefix: "fix"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      commit-message:
        prefix: "fix"